### ISSUE TITLE
Missing option to loop an animation indefinitely 

### ISSUE THREAD

**Issue by osamaaamer95** [slorber/react-native-animation-hooks#4]
The `useAnimation` hook is missing an option to loop the animation using `Animated.loop()`. Is this something you will be willing to include? I went through the implementation, and it seems to be simple enough to implement. Adding a `loop` config option and some conditionals in the hook.

**Comment by slorber** [comment]
Hi,

I'm fine to add a loop feature in this lib but wonder what the code and the API would look like.

Note that we should not add conditionals around the hook.

It's also possible that the user want to change runtime anim config from spring to timing, not sure it would make sense to change from spring to loop for example.

Maybe it would be better to create a new hook just for instead to try to fit them into existing api?
