### ISSUE TITLE
Not working with text

### ISSUE THREAD

**Issue by fega** [slorber/react-native-animation-hooks#5]
Hello, the library is not working with the following snippet, 

```
import React from 'react';
import { Text, View, StyleSheet, Animated } from 'react-native';
import { useAnimation } from 'react-native-animation-hooks'

const s = StyleSheet.create({
  container: {
    alignItems: "center"
  },
  titleText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 20
  },
  fadedText: {
    color: "#898989",
    fontSize: 11
  }
});


const StatText = (props) => {
    const animatedValue = useAnimation({
      type: 'timing',
      initialValue: 0,
      toValue: props.value,
      duration: 1000,
      useNativeDriver: true,
    })

  return (<View style={s.container}>
    <Animated.Text style={s.titleText}>{animatedValue}</Animated.Text>
    <Text style={s.fadedText}>{props.name}</Text>
  </View>)
}

export default StatText
```

**Comment by slorber** [comment]
What is not working exactly? Why are you rendering the animated value? It's not suppoed to be rendered this way but passed to an animated comp as style attribute, I don't understand what you are trying to do sorry

**Comment by fega** [comment]
There is any way to use it as text? to have a text animation?

**Comment by slorber** [comment]
This lib is just a helper to make your life easier, if you don't know how to animate text with normal RN code first, this lib won't help you, you first need to learn RN animations framework

I recommend https://www.udemy.com/master-react-native-animations/

**Comment by slorber** [comment]
If you are looking to animate numbers from one to another you'd rather use a lib like https://github.com/browniefed/react-native-ticker

**Comment by fega** [comment]
Ok, thanks so much, I was supposing this would be equal  as behave in react (reactDOM)
