### ISSUE TITLE
Can this library be used in React.js as well?

### ISSUE THREAD

**Issue by NIV54** [slorber/react-native-animation-hooks#8]
If not, I'd like to see an implementation for one (and or offer my support for it)

**Comment by slorber** [comment]
Hi,

This libray use RN Animated, which is supported by ReactNativeWeb so yes it should work.

Otherwise I have no plan to do more heavy work on this lib that is currently a tiny wrapper only)


You should also check React-spring that should offer a cross-platform animation api
